apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
    - github:
        clientID: Ov23ligGyzfBsYoIhpAT
        clientSecret:
          name: github-client-secret-xgllr
        hostname: ''
        organizations:
          - rguske-labs
        teams: []
      mappingMethod: claim
      name: github
      type: GitHub
    - ldap:
        attributes:
          email:
            - mail
          id:
            - dn
          name:
            - cn
          preferredUsername:
            - uid
        bindDN: 'uid=root,cn=users,dc=ldap,dc=jarvis,dc=lab'
        bindPassword:
          name: ldap-bind-password-p6nj9
        insecure: true
        url: 'ldap://jarvisnas.jarvis.lab/cn=users,dc=ldap,dc=jarvis,dc=lab?uid'
      mappingMethod: claim
      name: ldap
      type: LDAP