apiVersion: v1
kind: ServiceAccount
metadata:
  name: pacman-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pacman-role
rules:
- apiGroups:
  - security.openshift.io
  resourceNames:
  - anyuid
  resources:
  - securitycontextconstraints
  verbs:
  - use
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pacman-sa-rolebinding
subjects:
  - kind: ServiceAccount
    name: pacman-sa
roleRef:
  kind: Role
  name: pacman-role
  apiGroup: rbac.authorization.k8s.io