apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: ovs-bridge-mapping-physnet-br-vmdata
spec:
  desiredState:
    ovn:
      bridge-mappings:
        - bridge: br-vmdata
          localnet: physnet-vmdata
          state: present
  nodeSelector:
    node-role.kubernetes.io/worker: ''
