apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: pgadmin
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "2"
    spec:
      serviceAccountName: pgadmin-sa
      containers:
        - name: pgadmin4
          image: docker.io/crunchydata/crunchy-pgadmin4:centos8-13.6-4.7.5
          env:
            - name: SERVER_PORT
              value: "5050"
            # optional, if the image supports/needs it:
            - name: PGADMIN_DOMAIN
              value: "retroplay-online.apps.ocp-mk42.retroplay.guske.io"
            - name: PGADMIN_SETUP_EMAIL
              valueFrom:
                secretKeyRef:
                  name: pgadmin-credentials
                  key: PGADMIN_SETUP_EMAIL
            - name: PGADMIN_SETUP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgadmin-credentials
                  key: PGADMIN_SETUP_PASSWORD
            - name: PGADMIN_DEFAULT_EMAIL
              valueFrom:
                secretKeyRef:
                  name: pgadmin-credentials
                  key: PGADMIN_DEFAULT_EMAIL
            - name: PGADMIN_DEFAULT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgadmin-credentials
                  key: PGADMIN_DEFAULT_PASSWORD
          ports:
            - name: http1
              containerPort: 5050