apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: pgadmin
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "2"
    spec:
      containers:
        - name: pgadmin4
          image: quay.io/sticen/pgadmin4:latest
          env:
            - name: PGADMIN_LISTEN_PORT
              value: "8080"
            # optional, if the image supports/needs it:
            - name: PGADMIN_DEFAULT_EMAIL
              valueFrom:
                secretKeyRef:
                  name: pgadmin-credentials
                  key: PGADMIN_DEFAULT_EMAIL
            - name: PGADMIN_DEFAULT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgadmin-credentials
                  key: PGADMIN_DEFAULT_PASSWORD
          ports:
            - name: http1
              containerPort: 8080