kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongo-storage
spec:
  storageClassName: synology-iscsi-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi