---
# MongoDB Storage
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: NAMESPACE
  name: mongo-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---