apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: synology-iscsi-storage
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: csi.san.synology.com
parameters:
   dsm: 172.20.42.20
   location: '/volume1'
   fsType: 'ext4'
   protocol: 'iscsi'
reclaimPolicy: Delete
allowVolumeExpansion: true